general_settings:
  master_key: dummy
litellm_settings:
  drop_params: true
model_list:
- model_name: claude-opus-4.6
  litellm_params:
    model: github_copilot/claude-opus-4.6
    extra_headers:
      editor-version: "vscode/1.85.1"           # Editor version
      editor-plugin-version: "copilot/1.155.0"  # Plugin version
      Copilot-Integration-Id: "vscode-chat"     # Integration ID
      user-agent: "GithubCopilot/1.155.0"       # User agent
- model_name: claude-sonnet-4.5
  litellm_params:
    model: github_copilot/claude-sonnet-4.5
    extra_headers:
      editor-version: "vscode/1.85.1"           # Editor version
      editor-plugin-version: "copilot/1.155.0"  # Plugin version
      Copilot-Integration-Id: "vscode-chat"     # Integration ID
      user-agent: "GithubCopilot/1.155.0"       # User agent
- model_name: gpt-5.3-codex
  litellm_params:
    model: github_copilot/gpt-5.3-codex
    api_key: "any-text"          # Copilot auth is handled via browser flow usually
- model_name: gpt-5.2-codex
  litellm_params:
    model: github_copilot/gpt-5.2-codex
    extra_headers:
      editor-version: "vscode/1.85.1"           # Editor version
      editor-plugin-version: "copilot/1.155.0"  # Plugin version
      Copilot-Integration-Id: "vscode-chat"     # Integration ID
      user-agent: "GithubCopilot/1.155.0"       # User agent
- model_name: gpt-5.2
  litellm_params:
    model: github_copilot/gpt-5.2
    extra_headers:
      editor-version: "vscode/1.85.1"           # Editor version
      editor-plugin-version: "copilot/1.155.0"  # Plugin version
      Copilot-Integration-Id: "vscode-chat"     # Integration ID
      user-agent: "GithubCopilot/1.155.0"       # User agent
- model_name: gemini-3-pro
  litellm_params:
    model: github_copilot/gemini-3-pro
    extra_headers:
      editor-version: "vscode/1.85.1"           # Editor version
      editor-plugin-version: "copilot/1.155.0"  # Plugin version
      Copilot-Integration-Id: "vscode-chat"     # Integration ID
      user-agent: "GithubCopilot/1.155.0"       # User agent
- model_name: "*"
  litellm_params:
    model: github_copilot/claude-sonnet-4.5
    extra_headers:
      editor-version: "vscode/1.85.1"           # Editor version
      editor-plugin-version: "copilot/1.155.0"  # Plugin version
      Copilot-Integration-Id: "vscode-chat"     # Integration ID
      user-agent: "GithubCopilot/1.155.0"       # User agent
